### PR TITLE
chore(release): 1.6.0 Update submodules and relase new version

### PR DESCRIPTION
**Pull request by shun2wang**
This is to catch up with the new librime and plum version.

### CODE REVIEW

**Comment by lotem** [comment]
I think there is no substantial feature update since last release?

**Comment by shun2wang** [comment]
Honestly yes, but it seems like some fixes should make their way into Linux?But I'm not very persistent:-)

**Comment by shun2wang** [comment]
Hi @lotem ibus-rime not work on Ubuntu 24.04 wayland, will this update fix that? Ubuntu 24.04 has released this week.

**Comment by lotem** [comment]
Rebuilding ibus-rime is not needed for updated features in librime to take effect, as long as the new features don't introduce new APIs.
This is because librime is independently released as a shared library; ibus-rime is a thin wrapper to interface with ibus and the API between the two components are stable.

**Pull request closed without merging**
